version: "3.8"
services:
  webserver:
    image: app_webserver:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    ports:
      - "81:80"

    container_name: webserver_app
