name: Build Image

on:
  push:
    branches: [ dev ]
    paths:
       - "**/Dockerfile"

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webserver:latest --no-cache
  
  send-a-message:
    
    if: ${{ failure() }}
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: Send message
      run: echo "The build failed"
      
  run:
    if: ${{ success () }}
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: Run Docker container
      run: docker run -d -p 80:80 webserver:latest
      
  test-webserver:
    if: ${{ success () }}
    needs: run
    runs-on: self-hosted
    steps:
    - name: Test webserver
      run: curl -v 192.168.64.3:80



