name: Build Image

on:
  push:
    branches: [ dev ]
    paths:
       - "**/Dockerfile"

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webserver:v1



